#!/bin/bash
set -e
set -u
set -o pipefail
if [ -v CONVERTER_DEBUG_SET_X ]; then
  set -x
fi

INPUT_DIR=/input/
OUTPUT_DIR=/output/

if [ -d $OUTPUT_DIR ]; then
  OUTPUT_VOLUME=1
else
  OUTPUT_VOLUME=0
  mkdir $OUTPUT_DIR
fi

debug() {
  if [ -v CONVERTER_DEBUG ]; then
    echo "DEBUG: $@"
  fi
}

help () {
cat << EOF
A bash script to interface applications in timjaanson/media-converter docker container
EOF
}

parse_arguments() {
  while getopts 'a:h' OPTION; do
    case "$OPTION" in
      a)
        APPLICATION="$OPTARG"
        ;;

      h)
        help
        exit 1
        ;;

      ?)
        echo "see '$(basename $0) -h' for help"
        exit 1
        ;;
        
    esac
  done
  shift "$(($OPTIND -1))"
}

direct_convert() {
  for file in $INPUT_DIR*; do
    if [ -f "$file" ]; then
      FILENAME_AND_TYPE=$(basename "$file")
      FILENAME="${FILENAME_AND_TYPE%.*}"
      ARGS=${ARGS//INPUT_FILE/$file}
      ARGS=${ARGS//OUTPUT_FILE/$OUTPUT_DIR$FILENAME}
      debug $APPLICATION $ARGS
      $APPLICATION $ARGS  
    fi
  done
}

direct_convert_single() {
  debug $APPLICATION $ARGS
  $APPLICATION $ARGS
}

if [ -v APPLICATION ]; then
  debug "Converting application is manually set to $APPLICATION"
  ARGS="$@"
  if [ -v NO_BATCH ]; then
    direct_convert_single
  else
    direct_convert
  fi
  debug "Conversion done"

  if [ $OUTPUT_VOLUME -eq 1 ]; then
    debug "Volume attached to $OUTPUT_DIR, leaving converted files there!"
  else
    debug "Moving output files to final destination"
    mkdir -p ${INPUT_DIR}output
    mv $OUTPUT_DIR* ${INPUT_DIR}output
  fi

  debug "All done!"
else
  debug "Converting application not set with env variable APPLICATION"
  debug "parsing arguments..."
  parse_arguments $@

  debug "All done!"
fi
